### ISSUE TITLE
Examples not working within fresh Docker container

### ISSUE THREAD

**Issue by james-blitzm** [opendatacube/datacube-alchemist#84]
I'm not sure if this is expected to work without additional configuration, but it looks like a package may be missing from the built Docker image?

```
root@9429c110f08e:/code# datacube-alchemist run-many \
>   --config-file ./examples/c3_config_wo.yaml \
>   --limit=2 \
>   --dryrun \
>   time in 2020-01
Traceback (most recent call last):
  File "/env/bin/datacube-alchemist", line 33, in <module>
    sys.exit(load_entry_point('datacube-alchemist', 'console_scripts', 'datacube-alchemist')())
  File "/env/bin/datacube-alchemist", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 833, in distribution
    return Distribution.from_name(distribution_name)
  File "/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 448, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for datacube-alchemist
```

**Comment by james-blitzm** [comment]
Noting here that I was able to get past the above after running this again in the running container: https://github.com/opendatacube/datacube-alchemist/blob/main/Dockerfile#L14

**Comment by alexgleith** [comment]
If you install locally using `--editable` it should work.

`pip install --editable .`
